export const filterA = [
  ["Mum", "Dad", "Husband", "Wife", "Son", "Daughter", "Brother", "Sister"],
  ["Grandad", "Grandma", "Aunt", "Uncle", "Cousin", "Niece/Nephew"],
  [
    "Father-in-Law",
    "Mother-in-Law",
    "Brother-in-Law",
    "Sister-in-Law",
    "Son-in-Law",
    "Daughter-in-Law",
  ],
  ["Boyfriend", "Girlfriend", "Fiancee"],
  ["Friend", "Colleague", "Relative", "Neighbour", "Pets", "Other"],
];

export const filterB = [
  "Birthday",
  "Thank You",
  "Anniversary",
  "Apology",
  "Christmas",
  "Congratulations",
  "Friendship",
  "Graduation",
  "Love You",
  "New Baby",
  "New House",
  "Promotion",
  "Retirement",
  "Sympathy",
  "Thinking of You",
  "Valentine's Day",
  "Mothers Day",
  "Fathers Day",
  "Easter",
  "Halloween",
];

export const filterC = [
  "1-5 Birthdays",
  "6-10 Birthdays",
  "13th Birthday",
  "16th Birthday",
  "18th Birthday",
  "21th Birthday",
  "30th Birthday",
  "40th Birthday",
  "50th Birthday",
  "60th Birthday",
  "65th Birthday",
  "70th Birthday",
  "75th Birthday",
  "80th Birthday",
  "85th Birthday",
  "90th Birthday",
  "100th Birthday",
];
